email = "minecraft.account@example.com" # Microsoft email for Minecraft account
password = "Password123!"               # Password for Minecraft account
server = "play.example.com"             # IP Address of the server

###############################
# Everything else is optional #
# Shown args are defaults     #
###############################

reconnect_delay = 5   # Seconds to wait before reconnecting
reconnect = false     # Should we reconnect after disconnect/kick?
logDir = "./logs"     # Directory to place logs for this bot
historyDir = "./logs" # Where should we place our .hist file for scrollback

debug = false # Spam logs with debug info


[botOwner] # This is not required, but all args for it are if it's declared
usernames = [
    "Notch",
] # Usernames or Displaynames of the accounts controlling the bot
# How the server's /msg are formatted. %playername% will match any username in that spot to the owner's username, case sensitive
msgRegex = "\\[%playername% -> me\\]"
runOnMsg = true                       # Whether the bot should echo back all commands/messages from the owner

# When the bot connects, what commands should it run?
[runOnJoin] # This is not required, but all args for it are if it's declared
# command = ["/say Hello world!"] # It can run multiple commands in a list, or:
commands = [
    { command = "/say Hello world!", delay = 5000 },             # You can specify a time in milliseconds to wait before executing the command or:
    { command = "/say Hello world!", randDelay = "5000-15000" }, # You can specify a time range in milliseconds to randomly wait between before running the command.
]
# However, you may only have 1 "command = " listed.